services:
  dustapp:
    build: .
    image: dustimage
    volumes:
      - dust-data:/app/data 
    command: tail -f /dev/null

volumes:
  dust-data:
    external: true         
    name: dust-data        
